{
 "title": "Logstash monitoring",
 "description": "System, JVM, Pipeline and individual plugin stats",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "query_result({job='logstash'})" },
   {
    "name": "plugin_id",
    "query": "query_result(logstash_pipeline_plugins_filters_events_duration_in_millis{instance=~'$instance'})"
   },
   {
    "name": "input_plugin",
    "query": "query_result(logstash_pipeline_plugins_inputs_events_out{instance=~'$instance'})"
   },
   {
    "name": "output_plugin",
    "query": "query_result(logstash_pipeline_plugins_outputs_events_out{instance=~'$instance'})"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$instance - Avg CPU load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "repeat": "instance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "logstash_process_cpu_load_average_15m{instance=~'$instance'}",
     "legendFormat": "avg15"
    },
    {
     "expr": "logstash_process_cpu_load_average_1m{instance=~'$instance'}",
     "legendFormat": "avg1"
    },
    {
     "expr": "logstash_process_cpu_load_average_5m{instance=~'$instance'}",
     "legendFormat": "avg5"
    }
   ]
  },
  {
   "title": "Logstash ps fds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "logstash_process_max_file_descriptors{instance=~'$instance'}",
     "legendFormat": " {{instance_pqdn}}-max_fds"
    },
    {
     "expr": "logstash_process_open_file_descriptors{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-open_fds"
    },
    {
     "expr": "logstash_process_peak_open_file_descriptors{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-peak_open_fds"
    }
   ]
  },
  {
   "title": "Logstash ps total vmem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_process_mem_total_virtual_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-logstash_total_vmem"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Old pool usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_mem_pools_old_committed_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-old_pool_committed"
    },
    {
     "expr": "logstash_jvm_mem_pools_old_max_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-old_pool_max"
    },
    {
     "expr": "logstash_jvm_mem_pools_old_peak_max_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-old_pool_peak_max"
    },
    {
     "expr": "logstash_jvm_mem_pools_old_peak_used_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-old_pool_peak_used"
    },
    {
     "expr": "logstash_jvm_mem_pools_old_used_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-old_used"
    }
   ]
  },
  {
   "title": "Young pool usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_mem_pools_young_committed_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-young_pool_commited"
    },
    {
     "expr": "logstash_jvm_mem_pools_young_max_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-young_pool_max"
    },
    {
     "expr": "logstash_jvm_mem_pools_young_peak_max_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-young_pool_peak_max"
    },
    {
     "expr": "logstash_jvm_mem_pools_young_peak_used_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-young_pool_peak_used"
    },
    {
     "expr": "logstash_jvm_mem_pools_young_used_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-young_pool_used"
    }
   ]
  },
  {
   "title": "Survivor pool usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_mem_pools_survivor_committed_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-survivor_pool_commited"
    },
    {
     "expr": "logstash_jvm_mem_pools_survivor_max_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-survivor_pool_max"
    },
    {
     "expr": "logstash_jvm_mem_pools_survivor_peak_max_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-survivor_pool_peak_max"
    },
    {
     "expr": "logstash_jvm_mem_pools_survivor_peak_used_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-survivor_pool_peak_used"
    },
    {
     "expr": "logstash_jvm_mem_pools_survivor_used_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-survivor_pool_used"
    }
   ]
  },
  {
   "title": "Average time spent for GC (yound & old gens in ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_gc_collectors_old_collection_time_in_millis{instance=~'$instance'}/logstash_jvm_gc_collectors_old_collection_count{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-gc-old"
    },
    {
     "expr": "logstash_jvm_gc_collectors_young_collection_time_in_millis{instance=~'$instance'}/logstash_jvm_gc_collectors_young_collection_count{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-gc-young"
    }
   ]
  },
  {
   "title": "Threads count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_threads_count{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-threads_count"
    },
    {
     "expr": "logstash_jvm_threads_peak_count{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-threads_peak"
    }
   ]
  },
  {
   "title": "JVM Heap % used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_mem_heap_used_percent{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-jvm-usage"
    }
   ]
  },
  {
   "title": "JVM Heap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "logstash_jvm_mem_heap_max_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-jvm-max"
    },
    {
     "expr": "logstash_jvm_mem_heap_used_in_bytes{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-jvm-used"
    }
   ]
  },
  {
   "title": "$instance - GC old events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 33 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "logstash_jvm_gc_collectors_old_collection_count{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "$instance - GC young events",
   "type": "singlestat",
   "description": "Returns the rounded number of GC young events as measured over the time period specified by the user.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 36 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceil(increase(logstash_jvm_gc_collectors_young_collection_count{instance=~'$instance'}[$__range]))"
    }
   ]
  },
  { "title": "Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Events processing times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "logstash_pipeline_events_queue_push_duration_in_millis{instance=~'$instance'}/logstash_pipeline_events_in{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}} - avg waiting time"
    },
    {
     "expr": "logstash_pipeline_events_duration_in_millis{instance=~'$instance'}/logstash_pipeline_events_out{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}} - avg process time"
    }
   ]
  },
  {
   "title": "Processed events (I/O)/ sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "logstash_pipeline_events_out{instance=~'$instance'}/(logstash_pipeline_events_duration_in_millis{instance=~'$instance'}/1000)",
     "legendFormat": "{{instance_pqdn}} - processed events/sec"
    },
    {
     "expr": "logstash_pipeline_events_in{instance=~'$instance'}/(logstash_pipeline_events_queue_push_duration_in_millis{instance=~'$instance'}/1000)",
     "legendFormat": "{{instance_pqdn}} - pushed events/sec"
    },
    {
     "expr": "logstash_pipeline_plugins_outputs_events_out{instance='$instance',pipeline=\"main\",id=~'$output_plugin'}/(logstash_pipeline_plugins_outputs_events_duration_in_millis{instance='$instance',pipeline=\"main\",id=~'$output_plugin'}/1000)",
     "legendFormat": "{{instance_pqdn}} - processed events/sec in output plugin"
    }
   ]
  },
  {
   "title": "Output events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logstash_pipeline_plugins_outputs_events_out{instance=~'$instance',id=~'$output_plugin'}[$__range])",
     "legendFormat": "{{instance_pqdn}}"
    }
   ]
  },
  {
   "title": "$instance - Input plugins events avg waiting times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "repeat": "instance",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "logstash_pipeline_plugins_inputs_events_queue_push_duration_in_millis{instance=~'$instance',pipeline=\"main\",id=~'$input_plugin'}/logstash_pipeline_plugins_inputs_events_out{instance=~'$instance',pipeline=\"main\",id=~'$input_plugin'}",
     "legendFormat": "avg w time - {{id}}"
    }
   ]
  },
  {
   "title": "Beats input plugin connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "logstash_pipeline_plugins_inputs_current_connections{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-current"
    },
    {
     "expr": "logstash_pipeline_plugins_inputs_peak_connections{instance=~'$instance'}",
     "legendFormat": "{{instance_pqdn}}-peak"
    }
   ]
  },
  {
   "title": "Pipeline input events / sec over the last hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(logstash_pipeline_events_in{instance=~'$instance'}[$__range])",
     "legendFormat": "{{instance_pqdn}}"
    },
    {
     "expr": "sum by (job) (irate(logstash_pipeline_events_in{instance=~'$instance'}[$__range]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Pipeline output events / sec over the last hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(logstash_pipeline_plugins_outputs_events_out{instance=~'$instance'}[$__range])",
     "legendFormat": "{{instance_pqdn}}"
    },
    {
     "expr": "sum by (job) (irate(logstash_pipeline_plugins_outputs_events_out{instance=~'$instance'}[$__range]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "$instance - filters avg duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "repeat": "instance"
  },
  {
   "title": "$plugin_id",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 73 },
   "repeat": "plugin_id",
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "logstash_pipeline_plugins_filters_events_duration_in_millis{instance=~'$instance',pipeline=\"main\",id='$plugin_id'} /logstash_pipeline_plugins_filters_events_out{instance=~'$instance',pipeline=\"main\",id='$plugin_id'}"
    }
   ]
  }
 ]
}